version: '2'
services:
  newsmediator:
    image: bburndd/newsmediator:0.0.1
    ports:
      - "8080:8080"
      - "8090:8090"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge